global:
  redis: {}

image:
  registry: docker.io
  repository: bitnami/redis
  tag: 5.0.7-debian-10-r32
  pullPolicy: IfNotPresent

cluster:
  enabled: true
  slaveCount: 1

sentinel:
  enabled: false
  usePassword: false
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 5.0.7-debian-10-r27
    pullPolicy: IfNotPresent
  masterSet: mymaster
  initialCheckTimeout: 5
  quorum: 2
  downAfterMilliseconds: 60000
  failoverTimeout: 18000
  parallelSyncs: 1
  port: 26379
  configmap:
  staticID: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  service:
    type: ClusterIP
    sentinelPort: 26379
    redisPort: 6379
    annotations: {}
    labels: {}

clusterDomain: cluster.local

networkPolicy:
  enabled: false
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}

serviceAccount:
  create: false
  name:

rbac:
  create: fals
  role:
    rules: []
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
usePassword: false
password: "pass123"
usePasswordFile: false
persistence: {}
redisPort: 6379

## Redis Master parameters
master:
  command: "/run.sh"
  configmap:
  extraFlags: []
  disableCommands:
  - FLUSHDB
  - FLUSHALL

  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

  affinity: {}
  service:
    type: ClusterIP
    port: 6379
    annotations: {}
    labels: {}

  persistence:
    enabled: true
    path: /data
    subPath: ""
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    matchLabels: {}
    matchExpressions: {}

  statefulset:
    updateStrategy: RollingUpdate

## Redis Slave properties
slave:
  service:
    type: ClusterIP
    port: 6379
    annotations: {}
    labels: {}

  port: 6379
  command: "/run.sh"
  configmap:
  extraFlags: []
  disableCommands:
  - FLUSHDB
  - FLUSHALL
  affinity: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 5

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

  podLabels: {}
  podAnnotations: {}

  persistence:
    enabled: true
    path: /data
    subPath: ""
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    matchLabels: {}
    matchExpressions: {}

  statefulset:
    updateStrategy: RollingUpdate

## Prometheus Exporter / Metrics
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.4.0-debian-10-r3
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  serviceMonitor:
    enabled: false
    selector:
      prometheus: kube-prometheus
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ""
    rules: []
  service:
    type: ClusterIP
    annotations: {}
    labels: {}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
  resources: {}
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
configmap: |-
  appendonly yes
  save ""
  bind 0.0.0.0
sysctlImage:
  enabled: false
  command: []
  registry: docker.io
  repository: bitnami/minideb
  tag: buster
  pullPolicy: Always
  mountHostSys: false
  resources: {}
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
podSecurityPolicy:
  create: false
